* Testmycode (for Emacs)
** What is this?
This is an Emacs minor-mode for calling the =tmc= command-line program with its various arguments.  The package provides both keybindings and a menu for accessing the commands.  It also provides commands for instantly jumping  to the next/previous exercise without having to navigate the directories yourself.

The Java Programming I and II courses from [[mooc.fi]] are very popular and frequently recommended on [[https://www.reddit.com/r/learnjava/][r/learnjava]].  The school provides instructions for setting up an older version of the "NetBeans" IDE, but this is not the preferred editor for all.

Fortunately, you can use any editor you like, because the TestMyCode project provides [[https://github.com/testmycode/tmc-cli][a command-line interface]] to the same features that their NetBeans plugin provides.

So if you wanted to use Emacs (or Vim, or Nano, etc.), you could use that for the exercises and then go to your shell to type =tmc test=, =tmc submit=, etc.

But I like to stay in Emacs, so I made this package to interface with the command-line program and jump between exercise files.
** Installation
*** First, clone the repository to your machine.
=git clone git@github.com:mmarshall540/testmycode.git=
*** Now you can proceed in one of two ways:
**** Option 1 (package.el)
Open up Emacs and do the following:
=M-x package-install-file RET [PATH-TO-THE-TESTMYCODE-DIRECTORY] RET=
This will install the package from the local git repo into the local Emacs package store.  Package.el will make it available and set up autoloading.
**** Option 2 (manual)
If you don’t use package.el, or prefer to keep this package separate from it, you can add the following to your Emacs ‘init’ file.
=(load [PATH-TO-THE-TESTMYCODE-DIRECTORY]/testmycode.el)=
This will load the file directly from the local git repo, but won’t set up autoloading.
For that, you will need to also add the following line.
=(autoload 'tmc-mode (expand-file-name "testmycode.el" [PATH-TO-THE-TESTMYCODE-DIRECTORY]) "" t)=
** Configuration
*** Start the mode automatically whenever opening Java files
While working through the courses, it makes sense to enable the mode whenever ‘java-mode’ starts.  To do that, add the following to your init file.
=(add-hook 'java-mode-hook 'tmc-mode)=
*** Change the prefix key
The default prefix key for the commands is =C-c ’=, but you can change this through Emacs’s "Customize" system: =M-x customize-variable RET tmc-prefix-key RET=.

Or if you prefer to set it manually in your init file, just add the following before testmycode.el gets loaded.
=(customize-set-variable ’tmc-prefix-key (kbd "C-c t"))=
(if you wanted to set the prefix key to "C-c t")
